site_name: Agilic Training Wiki (Preview)
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.sections
    - search.suggest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Section 1: Agilic Fundamentals:
    - Navigate as a User: s1-agilic-fundamentals/navigate-as-a-user.md
    - Core Terms & Concepts: s1-agilic-fundamentals/core-terms-concepts.md
    - Roles & Permissions: s1-agilic-fundamentals/roles-permissions.md
    - Persona Guides: s1-agilic-fundamentals/persona-guides.md