site_name: Agilic Training Wiki (Preview)
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.sections
    - search.suggest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Section 1: Agilic Fundamentals:
    - Navigate as a User: s1-agilic-fundamentals/navigate-as-a-user.md
    - Core Terms & Concepts: s1-agilic-fundamentals/core-terms-concepts.md
    - Roles & Permissions: s1-agilic-fundamentals/roles-permissions.md
    - Persona Guides: s1-agilic-fundamentals/persona-guides.md
  - Section 2: Setting Up Your Org:
    - Navigate Org Admin: s2-setting-up-your-org/navigate-org-admin.md
    - Create Your Organization: s2-setting-up-your-org/create-your-organization.md
    - Things to Consider When Setting Up Your Org: s2-setting-up-your-org/things-to-consider-when-setting-up-your-org.md
    - Org Settings: s2-setting-up-your-org/org-settings.md
    - Setting Up Org Templates: s2-setting-up-your-org/setting-up-org-templates.md
    - Permissions for People: s2-setting-up-your-org/permissions-for-people.md
    - Adding & Managing People: s2-setting-up-your-org/adding-and-managing-people.md
    - Managing Billing: s2-setting-up-your-org/managing-billing.md